Fixed x86-power-issues

diff --git a/meta-facebook/meta-bletchley/recipes-bletchley/motor-ctrl/files/power-ctrl b/meta-facebook/meta-bletchley/recipes-bletchley/motor-ctrl/files/power-ctrl
--- a/meta-facebook/meta-bletchley/recipes-bletchley/motor-ctrl/files/power-ctrl
+++ b/meta-facebook/meta-bletchley/recipes-bletchley/motor-ctrl/files/power-ctrl
@@ -10,9 +10,9 @@ export PATH=$PATH:/usr/sbin:/usr/libexec
 source /usr/libexec/bletchley-common-functions
 
 DELAY_POWER_ON="0.5"
-DELAY_POWER_OFF="10"
+DELAY_POWER_OFF="5"
 DELAY_POWER_RECOVERY_MODE="10"
-POWER_BTN_TIMEOUT_SEC=10
+POWER_BTN_TIMEOUT_CNT=60
 
 REV_EVT="EVT"
 REV_DVT="DVT"
@@ -98,6 +98,23 @@ function get_board_rev()
     return 0
 }
 
+#Switch pull low while it be touched
+function wait_for_switch()
+{
+    TARGET_PIN=$1
+    TARGET_SWITCH=1
+    TIME_CNT=0
+    while  [ "$TARGET_SWITCH" -eq 1 ]  ;do
+        TARGET_SWITCH=$(get_gpio "$TARGET_PIN")
+        sleep 0.1
+        TIME_CNT=$(( TIME_CNT +1))
+         if [  $TIME_CNT -gt $POWER_BTN_TIMEOUT_CNT ];then
+             echo "Error: Too long to get target switch, force exit"  >&2
+             break
+         fi
+    done
+}
+
 function trigger_power_button()
 {
     local sled_num=$1
@@ -110,7 +127,7 @@ function trigger_power_button()
 
     echo "Motor go forward to press Power key"
     motor-ctrl "sled${sled_num}" f >/dev/null
-    wait_gpio_falling "${GPIO_DETECT_PIN0}" "$POWER_BTN_TIMEOUT_SEC"
+    wait_for_switch "${GPIO_DETECT_PIN0}"
     motor-ctrl "sled${sled_num}" s >/dev/null
 
     if [ "$(get_gpio  "$GPIO_DETECT_PIN0")" -eq 0 ];then
@@ -122,7 +139,7 @@ function trigger_power_button()
     fi
 
     motor-ctrl "sled${sled_num}" r >/dev/null
-    wait_gpio_falling "${GPIO_DETECT_PIN1}" "$POWER_BTN_TIMEOUT_SEC"
+    wait_for_switch "${GPIO_DETECT_PIN1}"
     motor-ctrl "sled${sled_num}" s >/dev/null
     if [ "$(get_gpio  "$GPIO_DETECT_PIN1")" -eq 0 ];then
         echo "Motor reverse to initial position successful"
@@ -142,7 +159,7 @@ function release_power_button()
     fi
 
     motor-ctrl "sled${sled_num}" r >/dev/null
-    wait_gpio_falling "${GPIO_DETECT_PIN1}" "$POWER_BTN_TIMEOUT_SEC"
+    wait_for_switch "${GPIO_DETECT_PIN1}"
     motor-ctrl "sled${sled_num}" s >/dev/null
     if [ "$(get_gpio  "$GPIO_DETECT_PIN1")" -eq 0 ];then
         echo "Motor reverse to initial position successful"
@@ -161,7 +178,7 @@ function press_power_button()
 
     echo "Motor go forward to press Power button"
     motor-ctrl "sled${sled_num}" f >/dev/null
-    wait_gpio_falling "${GPIO_DETECT_PIN0}" "$POWER_BTN_TIMEOUT_SEC"
+    wait_for_switch "${GPIO_DETECT_PIN0}"
     motor-ctrl "sled${sled_num}" s >/dev/null
 
     if [ "$(get_gpio  "$GPIO_DETECT_PIN0")" -eq 0 ];then
@@ -367,7 +384,6 @@ function do_action_ac_on()
     local SLED_NUM=$1
     echo "sled${SLED_NUM}: turn on AC"
     set_gpio "power-host${SLED_NUM}" 1
-    sleep 3 # Newer versions of the managed system needs 3 second delay
     echo "$ACTION_AC_ON" > "/tmp/sled${SLED_NUM}-last-action"
 }
 
@@ -455,9 +471,6 @@ function host_state_on_action_handler()
         "$ACTION_CYCLE")
             do_action_cycle "$SLED_NUM"
             ;;
-        "$ACTION_ON")
-            echo "already on"
-            ;;
         *)
             echo "Invalid action ($ACTION) for current host state (On)"
             return 1
@@ -516,9 +529,6 @@ function host_state_off_action_handler()
             ;;
         "$ACTION_CYCLE")
             do_action_cycle "$SLED_NUM"
-            ;;
-        "$ACTION_OFF")
-            echo "already off"
             ;;
         *)
             echo "Invalid action ($ACTION) for current host state (Off)"
diff --git a/poky/meta/recipes-support/libnl/files/run-ptest b/poky/meta/recipes-support/libnl/files/run-ptest
--- a/poky/meta/recipes-support/libnl/files/run-ptest
+++ b/poky/meta/recipes-support/libnl/files/run-ptest
@@ -1,3 +1,16 @@
-#! /bin/sh
+#!/bin/sh
 
-CK_AUTOMAKE=1 ./check-all
+num_fail=0
+
+for test in check*
+do
+    ./"$test" \
+         && echo "PASS: $test" \
+         || {
+            echo "FAIL: $test"
+            num_fail=$(( ${num_fail} + 1))
+         }
+
+done
+
+exit $num_fail
diff --git a/poky/meta/recipes-support/numactl/numactl/Fix-the-test-output-format.patch b/poky/meta/recipes-support/numactl/numactl/Fix-the-test-output-format.patch
--- a/poky/meta/recipes-support/numactl/numactl/Fix-the-test-output-format.patch
+++ b/poky/meta/recipes-support/numactl/numactl/Fix-the-test-output-format.patch
@@ -1,4 +1,4 @@
-From 29f811d9d381f2ab54b3c8cef77334e32970ef09 Mon Sep 17 00:00:00 2001
+From 59fd750a84bbe5874dec936d2bee9ef11a1b6505 Mon Sep 17 00:00:00 2001
 From: Li xin <lixin.fnst@cn.fujitsu.com>
 Date: Tue, 21 Jul 2015 02:01:22 +0900
 Subject: [PATCH] Fix the test output format
@@ -7,26 +7,24 @@ Upstream-Status: Pending
 
 Signed-off-by: Roy Li <rongqing.li@windriver.com>
 Signed-off-by: Li Xin <lixin.fnst@cn.fujitsu.com>
-Signed-off-by: Xiangyu Chen <xiangyu.chen@windriver.com>
-
 ---
  test/regress  |  6 +++---
  test/regress2 | 11 +++++------
  2 files changed, 8 insertions(+), 9 deletions(-)
 
 diff --git a/test/regress b/test/regress
-index f06b22f..2fdfacb 100755
+index 2ce1705..d086a47 100755
 --- a/test/regress
 +++ b/test/regress
-@@ -78,6 +78,7 @@ probe_hardware()
+@@ -74,6 +74,7 @@ probe_hardware()
  	if [ $numnodes -lt 2 ] ; then
  	    echo "need at least two nodes with at least $NEEDPAGES each of"
  	    echo "free memory for mempolicy regression tests"
-+	    echo "SKIP: numa regress"
- 	    exit 77  # Skip test
++	    echo "FAIL: numa regress"
+	    exit 77  # Skip test
  	fi
  }
-@@ -209,10 +210,9 @@ main()
+@@ -207,10 +208,9 @@ main()
  	rm A B
  
  	if [ "$EXIT" = 0 ] ; then
@@ -61,3 +59,6 @@ index aa6ea41..450c510 100755
  }
  
  # still broken
+-- 
+1.8.4.2
+
diff --git a/poky/scripts/runqemu-ifup b/poky/scripts/runqemu-ifup
--- a/poky/scripts/runqemu-ifup
+++ b/poky/scripts/runqemu-ifup
@@ -1,7 +1,10 @@
 #!/bin/bash
 #
 # QEMU network interface configuration script. This utility needs to
-# be run as root, and will use the ip utility
+# be run as root, and will use the tunctl binary from a native sysroot.
+# Note: many Linux distros these days still use an older version of
+# tunctl which does not support the group permissions option, hence
+# the need to use build system's version.
 #
 # If you find yourself calling this script a lot, you can add the
 # the following to your /etc/sudoers file to be able to run this
@@ -21,7 +24,7 @@
 #
 
 usage() {
-	echo "sudo $(basename $0) <gid>"
+	echo "sudo $(basename $0) <uid> <gid> <native-sysroot-basedir>"
 }
 
 if [ $EUID -ne 0 ]; then
@@ -29,43 +32,41 @@ if [ $EUID -ne 0 ]; then
 	exit 1
 fi
 
-if [ $# -eq 2 ]; then
-	echo "Warning: uid parameter is ignored. It is no longer needed." >&2
-	GROUP="$2"
-elif [ $# -eq 1 ]; then
-	GROUP="$1"
-else
+if [ $# -ne 3 ]; then
 	usage
 	exit 1
 fi
 
+USERID="-u $1"
+GROUP="-g $2"
+STAGING_BINDIR_NATIVE=$3
 
-if [ -z "$OE_TAP_NAME" ]; then
-	OE_TAP_NAME=tap
-fi
-
-if taps=$(ip tuntap list 2>/dev/null); then
-	tap_no_last=$(echo "$taps" |cut -f 1 -d ":" |grep -E "^$OE_TAP_NAME.*" |sed "s/$OE_TAP_NAME//g" | sort -rn | head -n 1)
-	if [ -z "$tap_no_last" ]; then
-		tap_no=0
-	else
-		tap_no=$(("$tap_no_last" + 1))
-	fi
-	ip tuntap add "$OE_TAP_NAME$tap_no" mode tap group "$GROUP" && TAP=$OE_TAP_NAME$tap_no
-fi
-
-if [ -z "$TAP" ]; then
-	echo "Error: Unable to find a tap device to use"
+TUNCTL=$STAGING_BINDIR_NATIVE/tunctl
+if [ ! -x "$TUNCTL" ]; then
+       echo "Error: Unable to find tunctl binary in '$STAGING_BINDIR_NATIVE', please bitbake qemu-helper-native"
 	exit 1
 fi
 
-IPTOOL=`which ip 2> /dev/null`
-if [ "x$IPTOOL" = "x" ]; then
-	# better than nothing...
-	IPTOOL=/sbin/ip
+TAP=`$TUNCTL -b $GROUP 2>&1`
+STATUS=$?
+if [ $STATUS -ne 0 ]; then
+# If tunctl -g fails, try using tunctl -u, for older host kernels 
+# which do not support the TUNSETGROUP ioctl
+	TAP=`$TUNCTL -b $USERID 2>&1`
+	STATUS=$?
+	if [ $STATUS -ne 0 ]; then
+		echo "tunctl failed:"
+		exit 1
+	fi
 fi
-if [ ! -x "$IPTOOL" ]; then
-	echo "$IPTOOL cannot be executed"
+
+IFCONFIG=`which ip 2> /dev/null`
+if [ "x$IFCONFIG" = "x" ]; then
+	# better than nothing...
+	IFCONFIG=/sbin/ip
+fi
+if [ ! -x "$IFCONFIG" ]; then
+	echo "$IFCONFIG cannot be executed"
 	exit 1
 fi
 
@@ -78,22 +79,22 @@ if [ ! -x "$IPTABLES" ]; then
 	exit 1
 fi
 
-n=$[ (`echo $TAP | sed "s/$OE_TAP_NAME//"` * 2) + 1 ]
-$IPTOOL addr add 192.168.7.$n/32 broadcast 192.168.7.255 dev $TAP
+n=$[ (`echo $TAP | sed 's/tap//'` * 2) + 1 ]
+$IFCONFIG addr add 192.168.7.$n/32 broadcast 192.168.7.255 dev $TAP
 STATUS=$?
 if [ $STATUS -ne 0 ]; then
     echo "Failed to set up IP addressing on $TAP"
     exit 1
 fi
-$IPTOOL link set dev $TAP up
+$IFCONFIG link set dev $TAP up
 STATUS=$?
 if [ $STATUS -ne 0 ]; then
     echo "Failed to bring up $TAP"
     exit 1
 fi
 
-dest=$[ (`echo $TAP | sed "s/$OE_TAP_NAME//"` * 2) + 2 ]
-$IPTOOL route add to 192.168.7.$dest dev $TAP
+dest=$[ (`echo $TAP | sed 's/tap//'` * 2) + 2 ]
+$IFCONFIG route add to 192.168.7.$dest dev $TAP
 STATUS=$?
 if [ $STATUS -ne 0 ]; then
     echo "Failed to add route to 192.168.7.$dest using $TAP"
